### ISSUE TITLE
Strange behavior on startup.

### ISSUE THREAD

**Issue by 0xE282B0** [frederikschubert/angular2-jspm#2]
Hi frederik,
I have a little trouble on starting the app.
When I start the server wit npm start and send my firefox to http://localhost:8080/www/ the app does not load.
But when I remove `moduleId: module.id` from showCase.ts before sending firefox to the page and add the line after the page is loaded the app appears.

So, starting the app does not work but code replacement is working.

**Comment by frederikschubert** [comment]
There seems to be a problem with the commonjs module bundling by the jspm typescript plugin. The `module.id` comes from commonjs and should allow relative asset paths for the components. I will try to debug this further.

**Comment by frederikschubert** [comment]
This should be fixed [now](https://github.com/frederikschubert/angular2-jspm/commit/da01a7d06501e90a32e4bbcf9456917c3d0a04c2).
**Relative assets only work in dev mode when the files are not bundled.**

**Comment by 0xE282B0** [comment]
Thanks, it's working.
